version: '3.6'

volumes:
  nextcloud:
  db_data1:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data1:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud    

  app:  
    image: nextcloud:apache
    restart: always
    expose:
      - 3001
    volumes:
      - nextcloud:/var/www/html
    environment:
      VIRTUAL_HOST: nextcloud.creusere.com
      VIRTUAL_PORT: 3001
    depends_on:
      - db
    
networks:
  default:
    external:
      name: nginx-proxy
